controllers:
    resource: ../src/Controller/
    type: attribute

Teachrs:
    path: /teachrs
    controller: App\Controller\TeachrController::teachr
    methods : GET

Register: 
    path: /register
    controller: App\Controller\TeachrController::save
    methods : POST

